site_name: 2wd RPi ROS2 Autonomous Vehicle
site_url: https://example.com/

theme:
  name: material
  palette:
    - scheme: default
      primary: teal
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: teal
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
repo_url: https://github.com/TheNoobInventor/2wd-rpi-ros2-autonomous-vehicle
repo_name: TheNoobInventor/2wd-rpi-ros2-autonomous-vehicle
plugins:
  - search:
      lang: en
